SELECT 
    SUBSTR(SEDE_CODIGO, 1, 2) AS departamento,
    COUNT(DISTINCT SEDE_CODIGO) AS total_sedes
FROM tic_2023
WHERE ACTIVIDAD_CODIGO = '05'
OR ACTIVIDAD_CODIGO IS NULL
GROUP BY SUBSTR(SEDE_CODIGO, 1, 2)
HAVING COUNT(DISTINCT SEDE_CODIGO) > 500
ORDER BY total_sedes DESC;
